$(function(){
	$("#dialog-2").dialog({
		autoOpen:false,
		width:598,
		buttons:[
			{
				text:"Vote",
				click:function(){
					$(".fader").hide();
					$(this).dialog("close");
				}
			},
			{
				text:"Close",
				click:function(){
					$(".fader").hide();
					$(this).dialog("close");
				}
			}
		]
	});	
	$("#dialog").dialog({
		autoOpen:false,
		width:598,
		buttons:[
			{
				text:"Vote",
				click:function(){
					$(this).dialog("close");
					$("#dialog-2").dialog("open");
				}
			},
			{
				text:"Close",
				click:function(){
					$(".fader").hide();
					$(this).dialog("close");
				}
			}
		]
	});
	$(".open-dialog").click(function(event){
		$(".fader").show();
		$("#dialog").dialog("open");
		event.preventDefault();
	});
});